In [3]:
import numpy as np

In [4]:
a = np.array([0.3,2.9,4.0])
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [7]:
sum_exp_a = np.sum(exp_a)

In [8]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [9]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [10]:
# 소프트맥스 오버플로우 문제점
# 최댓값을 이용하라
def softmax(a):
    C = np.max(a)
    exp_a = np.exp(a-C)  # 오버플로 대책
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [13]:
test = np.array([0.3,2.9,4.0])
result = softmax(test)

result

array([0.01821127, 0.24519181, 0.73659691])

In [14]:
np.sum(result)

1.0

In [15]:
# 주의점으로, 소프트맥스 함수를 적용해도 각 원소의 대소 관계는 변하지 않는다.
# 이는 지수 함수 y=exp(x)가 단조 증가 함수이기 때문이다.
# 신경망을 이용한 분류에서는 일반적으로 가장 큰 출력을 내는 뉴런에 해당하는
# 클래스라모나 인식한다. 그리고 소프트맥스 함수를 적용해도 출력이 가장 큰
# 뉴런의 위치는 달라지지 않는다. 결과적으로 신경망으로 분류할 때는 출력층의
# 소프트맥스 함수를 생략해도 된다. 현업에서도 지수 함수에 계산에 드는 자원낭비를
# 줄이고자 출력층의 소프트맥스 함수는 생략하는 것이 일반적이다.